// Generated by CoffeeScript 1.8.0
(function() {
  var Linear, crossover, fitness_test, generation, mutation, random, root, run;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  Linear = (require('./linear')).Linear;

  fitness_test = function(program) {
    var correct, i, results, sum, x, _i, _j, _len;
    results = [];
    for (x = _i = 0; _i <= 100; x = ++_i) {
      correct = 2 * x + 10;
      results[x] = abs(correct - program.run(i));
    }
    sum = 0;
    for (_j = 0, _len = results.length; _j < _len; _j++) {
      i = results[_j];
      sum += i;
    }
    return program.fitness = sum / results.length;
  };

  crossover = function(male_program, female_program) {
    female_program.a = male_program.a;
    return male_program.b = female_program.b;
  };

  mutation = function(program) {
    var a_factor, a_negative, b_factor, b_negative;
    a_factor = Math.floor(Math.random() * 10);
    b_factor = Math.floor(Math.random() * 10);
    a_negative = Math.floor(Math.random() * 10);
    b_negative = Math.floor(Math.random() * 10);
    if (a_negative % 2 === 0) {
      a_factor = a_factor * -1;
    }
    if (b_negative % 2 === 0) {
      b_factor = b_factor * -1;
    }
    program.a = a + a_factor;
    return program.b = a + a_factor;
  };

  random = function() {
    var a_factor, a_negative, b_factor, b_negative, gender, gender_factor;
    a_factor = Math.floor(Math.random() * 10);
    b_factor = Math.floor(Math.random() * 10);
    a_negative = Math.floor(Math.random() * 10);
    b_negative = Math.floor(Math.random() * 10);
    gender_factor = Math.floor(Math.random() * 10);
    gender = 'male';
    if (a_negative % 2 === 0) {
      a_factor = a_factor * -1;
    }
    if (b_negative % 2 === 0) {
      b_factor = b_factor * -1;
    }
    if (gender_factor % 2 === 0) {
      gender = 'female';
    }
    return new Linear(fitness_test, a_factor, b_factor, gender);
  };

  generation = function(programs) {
    var i, last_best, next, program, _i, _ref;
    next = [];
    last_best = random();
    for (i = _i = 0, _ref = programs.lengrh; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      program = programs[i];
      if (program.fitness < last_best.fitness) {
        last_best = program;
      }
    }
    next.push(last_best);
    return next;
  };

  run = function() {
    var i, programs, _i, _results;
    programs = [];
    _results = [];
    for (i = _i = 0; _i <= 10; i = ++_i) {
      _results.push(programs[i] = random);
    }
    return _results;
  };

}).call(this);
