// Generated by CoffeeScript 1.8.0
(function() {
  var Linear, crossover, mutation, random, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  Linear = (require('./linear')).Linear;

  crossover = function(male_program, female_program) {
    female_program.a = male_program.a;
    return male_program.b = female_program.b;
  };

  mutation = function(program) {
    var a_factor, a_negative, b_factor, b_negative;
    a_factor = Math.floor(Math.random() * 10);
    b_factor = Math.floor(Math.random() * 10);
    a_negative = Math.floor(Math.random() * 10);
    b_negative = Math.floor(Math.random() * 10);
    if (a_negative % 2 === 0) {
      a_factor = a_factor * -1;
    }
    if (b_negative % 2 === 0) {
      b_factor = b_factor * -1;
    }
    program.a = a + a_factor;
    return program.b = a + a_factor;
  };

  random = function() {
    var a_factor, a_negative, b_factor, b_negative, gender, gender_factor;
    a_factor = Math.floor(Math.random() * 10);
    b_factor = Math.floor(Math.random() * 10);
    a_negative = Math.floor(Math.random() * 10);
    b_negative = Math.floor(Math.random() * 10);
    gender_factor = Math.floor(Math.random() * 10);
    gender = 'male';
    if (a_negative % 2 === 0) {
      a_factor = a_factor * -1;
    }
    if (b_negative % 2 === 0) {
      b_factor = b_factor * -1;
    }
    if (gender_factor % 2 === 0) {
      gender = 'female';
    }
    return new Linear(a_factor, b_factor, gender);
  };

}).call(this);
