// Generated by CoffeeScript 1.8.0
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Program = (function() {
    function Program(fitness) {
      this.fitness = fitness;
    }

    Program.prototype.setRun = function(func) {
      return this.run = func;
    };

    return Program;

  })();

}).call(this);
